language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2.104
script:
  - dotnet restore GuidBase64.sln
  - dotnet build src/GuidBase64/GuidBase64.csproj -c Release
  - dotnet test tests/GuidBase64.UnitTests/GuidBase64.UnitTests.csproj
  - dotnet test tests/GuidBase64.IntegrationTests/GuidBase64.IntegrationTests.csproj
  - dotnet pack src/GuidBase64/GuidBase64.csproj -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/GuidBase64/bin/Release/GuidBase64.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$
