language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2.104

stages:
  - test
  - name: deploy
    if: tag IS present AND tag =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: dotnet test tests/GuidBase64.UnitTests/GuidBase64.UnitTests.csproj
    - name: "Integration Tests"
      script: dotnet test tests/GuidBase64.IntegrationTests/GuidBase64.IntegrationTests.csproj
    - stage: deploy
      name: "Publish to NuGet"
      script:
        - cd src/GuidBase64
        - dotnet build GuidBase64.csproj -c Release
        - dotnet pack GuidBase64.csproj -c Release
        - dotnet nuget push bin/Release/GuidBase64.*.nupkg --api-key $NUGET_API_KEY
