language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2.104
env:
  - TEST_PROJECT=tests/GuidBase64.UnitTests/GuidBase64.UnitTests.csproj
  - TEST_PROJECT=tests/GuidBase64.IntegrationTests/GuidBase64.IntegrationTests.csproj
script:
  - dotnet restore GuidBase64.sln
  - dotnet build src/GuidBase64/GuidBase64.csproj -c Release
  - dotnet test $TEST_PROJECT
deploy:
  skip_cleanup: true
  provider: script
  script:
    - dotnet pack src/GuidBase64/GuidBase64.csproj -c Release
    - dotnet nuget push src/GuidBase64/bin/Release/GuidBase64.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^(\d+\.)?(\d+\.)?(\*|\d+)$
